========================================
-- LIQUIBASE FORMATTED SQL
-- CHANGESET RohitG:1

CREATE TABLE EXCEPTION_LOG (
ID                NUMBER GENERATED BY DEFAULT AS IDENTITY,
SERVICE_NAME      							 VARCHAR2(50),
CLASS_NAME        							VARCHAR2(100),
METHOD_NAME      						    VARCHAR2(100),
EXCEPTION_TYPE  						    VARCHAR2(100),
EXCEPTION_MESSAGE 									 CLOB,
STACK_TRACE       									 CLOB,
MERCHANT_ID      						     VARCHAR2(20),
CORRELATION_ID    							 VARCHAR2(50),
REMARK            							VARCHAR2(500),
MDC_JSON          									 CLOB,
CREATED_BY        							VARCHAR2(100),
CREATED_DATE      									NUMBER,
PARTITION_DATE DATE GENERATED ALWAYS AS (TO_DATE(' 1970-01-01 00:00:00', 'syyyy-mm-dd hh24:mi:ss')+CREATED_DATE/1000/86400) VIRTUAL )
PCTFREE 30 INITRANS 100 MAXTRANS 255 PARTITION BY RANGE (PARTITION_DATE) INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
  (PARTITION P_START  VALUES LESS THAN (TO_DATE(' 2026-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED PCTFREE 10  INITRANS 100);
========================================
package com.sbi.epay.exceptionTracker.annotation;

import java.lang.annotation.*;

/**
 * Class Name: TrackException
 * Description: Annotation used to mark methods for exception tracking.
 * Author: V1024113(Rohit Gardi)
 * Copyright (c) 2025 [State Bank of India]
 * All rights reserved
 * <p>
 * Version:1.0
 **/
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface TrackException {

    boolean storeStackTrace() default true;

    boolean rethrow() default true;
}

========================================
package com.sbi.epay.exceptionTracker.aspect;

import com.sbi.epay.exceptionTracker.annotation.TrackException;
import com.sbi.epay.exceptionTracker.dto.ExceptionLogDto;
import com.sbi.epay.exceptionTracker.service.ExceptionQueueService;
import com.sbi.epay.exceptionTracker.util.ErrorConstant;
import com.sbi.epay.exceptionTracker.util.MDCUtil;
import com.sbi.epay.exceptionTracker.util.StackTraceUtil;

import lombok.RequiredArgsConstructor;

import org.aspectj.lang.ProceedingJoinPoint;
import org.aspectj.lang.annotation.Around;
import org.aspectj.lang.annotation.Aspect;
import org.aspectj.lang.reflect.MethodSignature;
import org.slf4j.MDC;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.util.Map;

/**
 * Class Name: ExceptionTrackerAspect
 * Description: Aspect class used to capture and process exceptions from annotated methods.
 * Author: V1024113(Rohit Gardi)
 * Copyright (c) 2025 [State Bank of India]
 * All rights reserved
 * <p>
 * Version:1.0
 **/
@Aspect
@Component
@RequiredArgsConstructor
public class ExceptionTrackerAspect {

    private final ExceptionQueueService queueService;

    @Value("${spring.application.name}")
    private String serviceName;

    // Intercepts methods annotated with @TrackException
    @Around("@annotation(trackException)")
    public Object trackException(ProceedingJoinPoint joinPoint, TrackException trackException) throws Throwable {

        try {
            // Executes actual business method
            return joinPoint.proceed();

        } catch (Exception ex) {

            MethodSignature signature = (MethodSignature) joinPoint.getSignature();
            Map<String, String> mdc = MDC.getCopyOfContextMap();

            ExceptionLogDto dto = ExceptionLogDto.builder()
                            .serviceName(serviceName)
                            .className(signature.getDeclaringTypeName())
                            .methodName(signature.getMethod().getName())
                            .exceptionType(ex.getClass().getName())
                            .exceptionMessage(ex.getMessage())
                            .stackTrace(trackException.storeStackTrace() ? StackTraceUtil.getShortStackTrace(ex) : null)
                            .correlationId(MDCUtil.getIgnoreCase(mdc, ErrorConstant.CORRELATION_ID))
                            .mdcMap(mdc)
                            .build();

            // Pushes exception details into queue
            queueService.add(dto);
            if (trackException.rethrow()) {
                throw ex;
            }
            return null;
        }
    }
}
========================================
package com.sbi.epay.exceptionTracker.config;

import com.sbi.epay.exceptionTracker.util.ErrorConstant;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.task.TaskExecutor;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;

/**

 * Class Name : ExceptionTaskExecutorConfig
 * Description : Configuration class used to create task executor.
 * Author : V1024113(Rohit Gardi)
 * Copyright (c) 2025 [State Bank of India]
 * All rights reserved
 *
 * Version:1.0
 */

@Configuration
public class ExceptionTaskExecutorConfig {

    @Bean(name = "exceptionTaskExecutor")
    public TaskExecutor exceptionTaskExecutor() {

        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(5);
        executor.setMaxPoolSize(10);
        executor.setQueueCapacity(ErrorConstant.QUEUE_SIZE);
        executor.setThreadNamePrefix("exceptionTaskExecutor-");
        executor.initialize();
        return executor;
    }

}
========================================
package com.sbi.epay.exceptionTracker.dao;

import com.sbi.epay.exceptionTracker.entity.ExceptionLog;
import com.sbi.epay.exceptionTracker.repository.ExceptionLogRepository;

import lombok.RequiredArgsConstructor;

import org.springframework.stereotype.Component;

import java.util.List;

/**
 * Class Name: ExceptionLogDao
 * Description: DAO class used to perform database operations for exception logs.
 * Author: V1024113(Rohit Gardi)
 * Copyright (c) 2025 [State Bank of India]
 * All rights reserved
 * <p>
 * Version:1.0
 **/
@Component
@RequiredArgsConstructor
public class ExceptionLogDao {

    private final ExceptionLogRepository repository;

    public void saveAll(List<ExceptionLog> logs) {
        repository.saveAll(logs);
    }
}
========================================
package com.sbi.epay.exceptionTracker.dto;

import lombok.*;

import java.util.Map;

/**
 * Class Name: ExceptionLogDto
 * Description: DTO class used to transfer exception details between layers.
 * Author: V1024113(Rohit Gardi)
 * Copyright (c) 2025 [State Bank of India]
 * All rights reserved
 * <p>
 * Version:1.0
 **/
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ExceptionLogDto {

    private String serviceName;
    private String className;
    private String methodName;
    private String exceptionType;
    private String exceptionMessage;
    private String stackTrace;
    private String merchantId;
    private String correlationId;
    private String remark;
    private String mdcJson;
    private String createdBy;
    private Long createdDate;
    private Map<String, String> mdcMap;
}
========================================
package com.sbi.epay.exceptionTracker.entity;

import jakarta.persistence.*;

import lombok.*;

/**
 * Class Name: ExceptionLog
 * Description: Entity class mapped with EXCEPTION_LOG database table.
 * Author: V1024113(Rohit Gardi)
 * Copyright (c) 2025 [State Bank of India]
 * All rights reserved
 * <p>
 * Version:1.0
 **/
@Entity
@Table(name = "EXCEPTION_LOG")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ExceptionLog {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String serviceName;
    private String className;
    private String methodName;
    private String exceptionType;
    @Lob
    private String exceptionMessage;
    @Lob
    private String stackTrace;
    private String merchantId;
    private String correlationId;
    private String remark;
    @Lob
    private String mdcJson;
    private String createdBy;
    private Long createdDate;
}

========================================
package com.sbi.epay.exceptionTracker.mapper;

import com.sbi.epay.exceptionTracker.dto.ExceptionLogDto;
import com.sbi.epay.exceptionTracker.entity.ExceptionLog;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * Class Name: ExceptionLogMapper
 * Description: Mapper interface used to convert ExceptionLogDto into ExceptionLog entity.
 * Author: V1024113(Rohit Gardi)
 * Copyright (c) 2025 [State Bank of India]
 * All rights reserved
 * <p>
 * Version:1.0
 **/
@Mapper(componentModel = "spring")
public interface ExceptionLogMapper {

    // Ignore id because database generates it automatically
    @Mapping(target = "id", ignore = true)
    ExceptionLog toEntity(ExceptionLogDto dto);
}

========================================

package com.sbi.epay.exceptionTracker.repository;

import com.sbi.epay.exceptionTracker.dto.ExceptionLogDto;
import com.sbi.epay.exceptionTracker.entity.ExceptionLog;
import com.sbi.epay.exceptionTracker.mapper.ExceptionLogMapper;
import com.sbi.epay.exceptionTracker.util.ErrorConstant;

import com.sbi.epay.logging.utility.LoggerFactoryUtility;
import com.sbi.epay.logging.utility.LoggerUtility;

import jakarta.annotation.PostConstruct;

import org.apache.commons.lang3.ObjectUtils;

import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.core.task.TaskExecutor;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.TimeUnit;

/**
 * Class Name : ExceptionBufferedRepository
 * Description : Buffered repository used for asynchronous
 * batch processing of exception logs.
 * Author : V1024113(Rohit Gardi)
 * Copyright (c) 2025 [State Bank of India]
 * All rights reserved
 * Version:1.0
 */
@Component
public class ExceptionBufferedRepository {

    private static final LoggerUtility logger = LoggerFactoryUtility.getLogger(ExceptionBufferedRepository.class);
    private final ExceptionLogRepository repository;
    private final ExceptionLogMapper mapper;
    private final TaskExecutor taskExecutor;
    private final BlockingQueue<ExceptionLogDto> queue = new LinkedBlockingQueue<>(ErrorConstant.QUEUE_SIZE);

    public ExceptionBufferedRepository(ExceptionLogRepository repository, ExceptionLogMapper mapper,
            @Qualifier("exceptionTaskExecutor")
            TaskExecutor taskExecutor
    ) {

        this.repository = repository;
        this.mapper = mapper;
        this.taskExecutor = taskExecutor;
    }

    @PostConstruct
    public void init() {
        taskExecutor.execute(this::saveAndFlush);
    }
    public void buffer(ExceptionLogDto dto) {
        if (!queue.offer(dto)) {
            logger.error("Error while buffering exception log, queue full");
        }
    }
    private void saveAndFlush() {
        while (true) {
            try {
                List<ExceptionLog> batch = new ArrayList<>();
                ExceptionLogDto first = queue.poll(1, TimeUnit.SECONDS);
                if (ObjectUtils.isNotEmpty(first)) {
                    try {
                        batch.add(mapper.toEntity(first));
                    } catch (Exception ex) {
                        logger.error("Error while mapping first exception log", ex);
                    }
                    List<ExceptionLogDto> temp = new ArrayList<>();
                    queue.drainTo(temp, ErrorConstant.BATCH_SIZE);
                    for (ExceptionLogDto dto : temp) {
                        try {
                            batch.add(mapper.toEntity(dto));
                        } catch (Exception ex) {
                            logger.error("Error while mapping exception log", ex);
                        }
                    }
                    if (!batch.isEmpty()) {
                        repository.saveAll(batch);
                        logger.info("Exception log batch saved successfully, batch size : {}", batch.size());
                    }
                }

            } catch (Exception ex) {
                logger.error("Error while saving exception log batch", ex);
            }
        }
    }
}

========================================
package com.sbi.epay.exceptionTracker.repository;

import com.sbi.epay.exceptionTracker.entity.ExceptionLog;

import org.springframework.data.jpa.repository.JpaRepository;

/**
 * Class Name: ExceptionLogRepository
 * Description: Repository interface used for ExceptionLog database operations.
 * Author: V1024113(Rohit Gardi)
 * Copyright (c) 2025 [State Bank of India]
 * All rights reserved
 * <p>
 * Version:1.0
 **/
public interface ExceptionLogRepository extends JpaRepository<ExceptionLog, Long> {
}

========================================
package com.sbi.epay.exceptionTracker.service;

import com.fasterxml.jackson.databind.ObjectMapper;

import com.sbi.epay.exceptionTracker.dto.ExceptionLogDto;
import com.sbi.epay.exceptionTracker.repository.ExceptionBufferedRepository;
import com.sbi.epay.exceptionTracker.util.ErrorConstant;
import com.sbi.epay.exceptionTracker.util.MDCUtil;

import com.sbi.epay.logging.utility.LoggerFactoryUtility;
import com.sbi.epay.logging.utility.LoggerUtility;

import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.Map;

/**
 * Class Name : ExceptionQueueService
 * Description : Service class used to prepare and buffer exception logs.
 * Author : V1024113(Rohit Gardi)
 * Copyright (c) 2025 [State Bank of India]
 * All rights reserved
 * Version:1.0
 */
@Service
public class ExceptionQueueService {

    private static final LoggerUtility logger = LoggerFactoryUtility.getLogger(ExceptionQueueService.class);
    private final ExceptionBufferedRepository exceptionBufferedRepository;
    private final ObjectMapper objectMapper;

    public ExceptionQueueService(ExceptionBufferedRepository exceptionBufferedRepository, ObjectMapper objectMapper) {
        this.exceptionBufferedRepository = exceptionBufferedRepository;
        this.objectMapper = objectMapper;
    }
    public void add(ExceptionLogDto dto) {

        try {
            Map<String, String> mdc = dto.getMdcMap();

            if (mdc == null) {
                mdc = new HashMap<>();
            }

            dto.setMerchantId(MDCUtil.getIgnoreCase(mdc, ErrorConstant.MID));
            dto.setCorrelationId(MDCUtil.getIgnoreCase(mdc, ErrorConstant.CORRELATION_ID));
            dto.setRemark(MDCUtil.getIgnoreCase(mdc, ErrorConstant.REMARK));
            dto.setCreatedBy(MDCUtil.getIgnoreCase(mdc, ErrorConstant.CREATED_BY));
            dto.setCreatedDate(System.currentTimeMillis());
            dto.setMdcJson(objectMapper.writeValueAsString(mdc));
            exceptionBufferedRepository.buffer(dto);

        } catch (Exception ex) {
            logger.error("Error while preparing exception log", ex);
        }
    }
}
========================================
package com.sbi.epay.exceptionTracker.util;

import lombok.experimental.UtilityClass;

/**

 * Class Name : ErrorConstant
 * Description : Utility class used to store exception tracker constants.
 * Author : V1024113(Rohit Gardi)
 * Copyright (c) 2025 [State Bank of India]
 * All rights reserved
 * <p>
 * Version:1.0
 **/
@UtilityClass
public class ErrorConstant {

    public static final String MID = "MID";
    public static final String CORRELATION_ID = "CORRELATION_ID";
    public static final String REMARK = "REMARK";
    public static final String CREATED_BY = "CREATED_BY";
    public static final int QUEUE_SIZE = 10000;
    public static final int BATCH_SIZE = 50;
    public static final String DEFAULT_EXCEPTION_MESSAGE = "Exception message is not available";
    public static final String DEFAULT_MDC_VALUE = "MDC value is not available";
}

========================================
package com.sbi.epay.exceptionTracker.util;

import lombok.experimental.UtilityClass;

/**
 * Class Name: ExceptionUtil
 * Description: Utility class used to extract exception message safely.
 * Author: V1024113(Rohit Gardi)
 * Copyright (c) 2025 [State Bank of India]
 * All rights reserved
 * <p>
 * Version:1.0
 **/
@UtilityClass
public class ExceptionUtil {

    public static String getMessage(Throwable ex) {

        if (ex == null) {
            return null;
        }
        return ex.getMessage();
    }
}
========================================

package com.sbi.epay.exceptionTracker.util;

import lombok.experimental.UtilityClass;

import java.util.Map;

/**
 * Class Name: MDCUtil
 * Description: Utility class used to fetch MDC values safely.
 * Author: V1024113(Rohit Gardi)
 * Copyright (c) 2025 [State Bank of India]
 * All rights reserved
 * <p>
 * Version:1.0
 **/
@UtilityClass
public class MDCUtil {

    // Fetches MDC value ignoring key case
    public static String getIgnoreCase(Map<String, String> map, String... keys) {

        if (map == null) {
            return null;
        }
        for (String key : keys) {
            for (Map.Entry<String, String> entry : map.entrySet()) {
                if (entry.getKey().equalsIgnoreCase(key)) {
                    return entry.getValue();
                }
            }
        }
        return null;
    }
}
========================================
package com.sbi.epay.exceptionTracker.util;

import lombok.experimental.UtilityClass;

/**
 * Class Name: StackTraceUtil
 * Description: Utility class used to generate formatted stack trace string from exception.
 * Author: V1024113(Rohit Gardi)
 * Copyright (c) 2025 [State Bank of India]
 * All rights reserved
 * <p>
 * Version:1.0
 **/
@UtilityClass
public class StackTraceUtil {

    public static String getShortStackTrace(Throwable ex) {

        StringBuilder sb = new StringBuilder();
        sb.append(ex.getMessage()).append(" ");
        StackTraceElement[] elements = ex.getStackTrace();
        for (StackTraceElement element : elements) {
            sb.append(element.toString()).append("\n");
        }
        return sb.toString();
    }
}

========================================
